### ISSUE TITLE
Replace Grunt with Webpack or NPM Scripts

### ISSUE THREAD

**Issue by nervewax** [kapow-wp/kapow-boilerplate#50]
Replace all current grunt tasks with a webpack or npm script alternative.

D.G Here's what we need the build to do based on what we have **now**:
##### CSS
- [x] Parse SCSS, complete with globbing
- [x] Process (autoprefix etc) and minify CSS
- [x] Copy both minified and un-minified copies of the CSS files into the theme
- [x] Generate a Modernzir build
##### JS
- [x] Concatenate our JS
- [x] Transpile our JS ([Babel](https://prettier.io/))
- [x] Uglify our JS
- [ ] Copy both minified and un-minified copies of the JS files into the theme
### Other
- [x] Sync any arbitrary files from assets to the theme (fonts / method to add directories)
- [x] Minify PNG, JPG and SVG images
- [x] Do any housekeeping cleanup (remove any temp or etc)
- [x] Notify when task(s) are completed (+ any other useful feedback)
##### Tasks
- [x] Dynamically watch for changes and trigger tasks based on what changed
- [ ] Pass list of directories to compile and watch

D.G / CT Here's what **extra** things we need the build to do:
- [ ] [Prettier](https://prettier.io/)
- [ ] Coding standards php, css, js
- [ ] Auto linting for php, css, js

**Comment by nervewax** [comment]
>When we do webpack, make sure the assets/css is only in build

**Comment by nervewax** [comment]
>Create / delete glob folder each grunt

**Comment by davetgreen** [comment]
I've been doing some reading, and it would appear to me like Webpack is **not** the solution.

NPM scripts looks much, much cleaner and means we can do everything from within the package.json.

Couple of links to digest:

https://deliciousbrains.com/npm-build-script/
https://scotch.io/tutorials/using-npm-as-a-build-tool
