### ISSUE TITLE
Styleguide

### ISSUE THREAD

**Issue by nervewax** [kapow-wp/kapow-boilerplate#65]
# Styleguide

An unobtrusive, auto-generated, living styleguide library of all a websites elements.

Branch: [kapow-boilerplate/tree/styleguide](https://github.com/kapow-wp/kapow-boilerplate/tree/styleguide)

## Todo
- [x] Urls for each "view" so it doesn't clear each refresh.
  - Maybe some js lib for this view switching stuff?
- [x] Scan for globals like colours, svgs and fonts if possible.*
  - This could be achieved with js, by scraping values from the DOM, or by searching or passing in specific sass files.
- [ ] Include warnings when structural rules* are broken.
  - E.g. when a component includes another template part.
  - This can also apply to modules / structures rules.
- [ ] Include a list of related elements
  - **used in** (all elements this one is used inside)
  - **contains** (all elements this one contains)
  - Relational links to the components would be nice. The jump must also be smooth, possibly more like a filter.
- [ ] Hierarchy for modifiers
  - Modifier versions should be listed after the default element and contain a link to the parent element.
- [ ] Post type option to pass a wrapper loop or function populating the content of the element correctly.
- [ ] As with above, a flag to pass a specific loop to wrap the elements would be good.
- [ ] Some way of having the modifier versions of a wired element output all possibilities with the correct classes to the styleguide.

### Todo Meta
- [ ] Come up with a nice name for this styleguide
- [ ] Write some doc...
- [ ] Have some kind of info page appear at the front. Links to docs, blogs, repo etc.
- [ ] Define some of the base rules, like use of bem, no components in components, element must fill parent etc.

### Requirements
- Modular coded blocks*
- [BEM](https://css-tricks.com/bem-101/) class naming structure, with parity of file names too.*
- PHP / Wordpress (Could also work for static html files I guess!?)

*needs clarification

Elements = Collective name for a component, module or structure.

**Comment by davetgreen** [comment]
@nervewax you could cache the current view in `localStorage` and then just check for it on page load, jumping straight back to it.

**Comment by davetgreen** [comment]
@nervewax this issue up to date?

**Comment by nervewax** [comment]
@davetgreen this is up to date, I might need to revisit this once the guten-dust settles, as there's a bit of overlap. I'll also resurrect the styleguide when the new repo / build tool / changes are done.

I'll close this issue and keep the list personal until then 👌
